os:
    # dependent on neovim-remote https://github.com/mhinz/neovim-remote
    open: "nvr --remote-tab {{filename}} --remote-send ':ReopenInLastTab {{filename}}<cr>'"
    edit: "nvr --remote-tab {{filename}} --remote-send ':ReopenInLastTab {{filename}}<cr>'"
    editAtLine: "nvr --remote-tab {{filename}} --remote-send ':ReopenInLastTabAtLine {{line}} {{filename}}<cr>'"
    openDir: "nvr --remote-tab {{dir}}"
keybinding:
    universal:
        prevItem-alt: "k"
        nextItem-alt: "j"
        prevBlock-alt: "h"
        nextBlock-alt: "l"
        nextMatch: "="
        prevMatch: "-"
        new: "e"
        edit: "o"
        openFile: "O"
        scrollUpMain-alt1: "K"
        scrollDownMain-alt1: "J"
        scrollUpMain-alt2: "<c-y>"
        scrollDownMain-alt2: "<c-e>"
        undo: "<c-u>"
        redo: "<c-r>"
        diffingMenu: "M"
        filteringMenu: "<c-f>"
        pushFiles: "<disabled>"
        quit: <c-c>
    files:
        ignoreFile: "I"
    commits:
        moveDownCommit: "<c-j>"
        moveUpCommit: "<c-k>"
        startInteractiveRebase: "i"
    branches:
        viewGitFlowOptions: "I"
        setUpstream: "U"
customCommands:
    - key: "P"
      prompts:
          - type: "confirm"
            title: "Are you sure you want to push the remote?"
            initialValue: ""
      command: git push
      description: "push to remote"
      context: "global"
      stream: true
    - key: "<c-n>"
      prompts:
          - type: "confirm"
            title: "Are you sure you want to push the remote without pre-push hook?"
            initialValue: ""
      command: git push --no-verify
      description: "push to remote without pre-push hook"
      context: "global"
      stream: true
    - key: "!"
      prompts:
          - type: "confirm"
            title: "Are you sure you want to FORCE push the remote without pre-push hook?!"
            initialValue: ""
      command: git push --force-with-lease --no-verify
      description: "FORCE push to remote without pre-push hook"
      context: "global"
      stream: true
    - key: "<c-p>"
      prompts:
          - type: "confirm"
            title: "Are you sure you want to FORCE push the remote?!"
            initialValue: ""
      command: git push --force-with-lease
      description: "FORCE push to remote"
      context: "global"
      stream: true
    - key: "<c-l>"
      prompts:
      command: open $(git remote get-url origin)
      description: "open remote origin in the browser"
      context: "global"
      stream: true
gui:
    theme:
        selectedLineBgColor:
            - reverse
    commandLogSize: 14
    nerdFontsVersion: "3"
    showDivergenceFromBaseBranch: "arrowAndNumber"
