os:
    # dependent on neovim-remote https://github.com/mhinz/neovim-remote
    open: "nvr --remote-tab {{filename}} --remote-send ':ReopenInLastTab {{filename}}<cr>'"
    edit: "nvr --remote-tab {{filename}} --remote-send ':ReopenInLastTab {{filename}}<cr>'"
    editAtLine: "nvr --remote-tab {{filename}} --remote-send ':ReopenInLastTabAtLine {{line}} {{filename}}<cr>'"
    openDir: "nvr --remote-tab {{dir}}"
keybinding:
    universal:
        prevItem-alt: "u"
        nextItem-alt: "e"
        prevBlock-alt: "n"
        nextBlock-alt: "i"
        nextMatch: "="
        prevMatch: "-"
        new: "k"
        edit: "o"
        openFile: "O"
        scrollUpMain-alt1: "U"
        scrollDownMain-alt1: "E"
        scrollUpMain-alt2: "<c-y>"
        scrollDownMain-alt2: "<c-e>"
        undo: "l"
        redo: "<c-r>"
        diffingMenu: "M"
        filteringMenu: "<c-f>"
        pushFiles: "<disabled>"
    files:
        ignoreFile: "I"
    commits:
        moveDownCommit: "<c-e>"
        moveUpCommit: "<c-u>"
        startInteractiveRebase: "h"
    branches:
        viewGitFlowOptions: "I"
        setUpstream: "U"
customCommands:
    - key: "P"
      prompts:
          - type: "confirm"
            title: "Are you sure you want to push the remote?"
            initialValue: ""
      command: git push
      description: "push to remote"
      context: "global"
      stream: true
    - key: "<c-n>"
      prompts:
          - type: "confirm"
            title: "Are you sure you want to push the remote without pre-push hook?"
            initialValue: ""
      command: git push --no-verify
      description: "push to remote without pre-push hook"
      context: "global"
      stream: true
gui:
    theme:
        selectedLineBgColor:
            - reverse
    commandLogSize: 14
    nerdFontsVersion: "3"
    showDivergenceFromBaseBranch: "arrowAndNumber"
